### PR TITLE
Configuration

### PR DESCRIPTION
**Pull request by LukeMathWalker**
I have added a tiered configuration mechanism, which leverages `Serde` and the type system to avoid issues and boilerplate when parsing the values out of environment variables.

Out of scope for this PR: finding a way to pass `Settings.authentication.secret` to the auth module, to use it when validating the signature of JWT tokens.

### CODE REVIEW

**Comment by colinbankier** [comment]
This is awesome, thanks!
One thing I have since realised that I think we lost in #10 was for "test" and "dev" to use separate databases - i.e. you can be running the app locally and messing with data, and running tests on a separate clean database. (maybe that still works  - I may not have looked close enough). It'd be nice to use this to reinstate that here if not.
Also, I think it would be great to include some sample structure for different envs (e.g. "test", "dev", "prod") like https://github.com/mehcode/config-rs/tree/master/examples/hierarchical-env/config so this can serve as a nice example of how to actually do this for a real app.

**Comment by LukeMathWalker** [comment]
> One thing I have since realised that I think we lost in #10 was for "test" and "dev" to use separate databases - i.e. you can be running the app locally and messing with data, and running tests on a separate clean database. (maybe that still works - I may not have looked close enough). It'd be nice to use this to reinstate that here if not.

You can still do that using environment variables, but I agree that we might make more explicit using a stratified configuration approach. I'll pull something together and update the PR :+1:

**Comment by colinbankier** [comment]
Great :+1:  yep, that'd be great to keep the "test" db separate without a user needing to know or remember to do anything special with env vars. This is inspired by how Rails manages "test" and "dev" (and "prod") envs - and frameworks in other languages have followed this pattern since too.

**Comment by LukeMathWalker** [comment]
It should be better now @colinbankier :+1:

**Comment by colinbankier** [comment]
Great, thanks! 
This is a big improvement to configuration handling :+1:

**Pull request merged**
